/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention

 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

/* Access a 32-bit hardware register. */
#define REG32(address) (*(volatile uint32_t *)(address))

#define RCC_AHB2ENR  REG32(0x4002104Cu)

#define GPIOB_MODER   REG32(0x48000400u)
#define GPIOB_OTYPER  REG32(0x48000404u)
#define GPIOB_OSPEEDR REG32(0x48000408u)
#define GPIOB_PUPDR   REG32(0x4800040Cu)
#define GPIOB_BSRR    REG32(0x48000418u)

#define GPIOC_MODER   REG32(0x48000800u)
#define GPIOC_OTYPER  REG32(0x48000804u)
#define GPIOC_OSPEEDR REG32(0x48000808u)
#define GPIOC_PUPDR   REG32(0x4800080Cu)
#define GPIOC_BSRR    REG32(0x48000818u)

#define GREEN (1u << 7)   /* PC7 */
#define BLUE  (1u << 7)   /* PB7 */
#define RED   (1u << 14)  /* PB14 */

static void delay(void)
{
    volatile uint32_t count = 200000u;

    while (count > 0u) {
        count--;
    }
}

int main(void)
{
    /* Enable clocks for GPIOB and GPIOC. */
    RCC_AHB2ENR |= (1u << 1) | (1u << 2);

    /* Read back to allow clock enabling to take effect. */
    (void)RCC_AHB2ENR;

    /* Initialize all LED output levels to low. */
    GPIOB_BSRR = (BLUE | RED) << 16;
    GPIOC_BSRR = GREEN << 16;

    /* Push-pull output: clear each pin's output-type bit. */
    GPIOB_OTYPER &= ~(BLUE | RED);
    GPIOC_OTYPER &= ~GREEN;

    /* Low speed: clear each pin's two-bit speed field. */
    GPIOB_OSPEEDR &= ~((3u << 14) | (3u << 28));
    GPIOC_OSPEEDR &= ~(3u << 14);

    /* No pull-up or pull-down. */
    GPIOB_PUPDR &= ~((3u << 14) | (3u << 28));
    GPIOC_PUPDR &= ~(3u << 14);

    /* Output mode: clear the mode fields, then set to 01. */
    GPIOB_MODER &= ~((3u << 14) | (3u << 28));
    GPIOB_MODER |=  (1u << 14) | (1u << 28);

    GPIOC_MODER &= ~(3u << 14);
    GPIOC_MODER |=  (1u << 14);

    while (1) {
        /* Green on. */
        GPIOC_BSRR = GREEN;
        delay();

        /* Green off, blue on. */
        GPIOC_BSRR = GREEN << 16;
        GPIOB_BSRR = BLUE;
        delay();

        /* Blue off, red on. */
        GPIOB_BSRR = BLUE << 16;
        GPIOB_BSRR = RED;
        delay();

        /* Red off, then repeat. */
        GPIOB_BSRR = RED << 16;
    }
}
